sudo: required
services:
    - docker

before_install:
    - docker build -t victorkulcsar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true victorkulcsar/docker-react npm run test